version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: video-courses-postgres
    ports:
      - "5034:5432"
    environment:
      POSTGRES_USER: video_user
      POSTGRES_PASSWORD: video_password
      POSTGRES_DB: video_courses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U video_user -d video_courses_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: video-courses-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_SERVER_URL: https://xn----7sb1acdcpkxafxk9g.xn--p1ai
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "mc ready local || wget -q --spider http://localhost:9000/minio/health/live || exit 0"]
      interval: 30s
      timeout: 20s
      retries: 3


  redis:
    image: redis:7-alpine
    container_name: video-courses-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
  redis_data:
